name: Create PDF Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container: pandoc/latex:latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release notes from CHANGELOG
        id: get_release_notes
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          # Find tag line and print until the next ## or end of file.
          NOTES=$(awk "/^## \\[${TAG#v}\\]/{flag=1; next} /^## \\[/{flag=0} flag" CHANGELOG.md)
          # Make the notes available to subsequent steps
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: sh

      - name: Build PDF from Markdown
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          pandoc SPECIFICATION.md \
            --pdf-engine=pdflatex \
            -V geometry:margin=1.5in \
            -o "Programming Project Tracker Specification ${TAG}.pdf"
            
      - name: Create Release and Upload PDF
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.get_release_notes.outputs.notes }}
          files: "Programming Project Tracker Specification *.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  